// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtqUqjcq9mRhSoyL_c7k5PgFnYwGD_IU4',
    appId: '1:252795060186:web:15154353c72ca35e660ae3',
    messagingSenderId: '252795060186',
    projectId: 'nexus-chatapp-prototype',
    authDomain: 'nexus-chatapp-prototype.firebaseapp.com',
    storageBucket: 'nexus-chatapp-prototype.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2zkegcUdn_UCGoa3IoL0oPstiym_Zfto',
    appId: '1:252795060186:android:422e13e34721a95f660ae3',
    messagingSenderId: '252795060186',
    projectId: 'nexus-chatapp-prototype',
    storageBucket: 'nexus-chatapp-prototype.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkYaSwsfjgFqrbUWXi4E9Qvck3SSOztyI',
    appId: '1:252795060186:ios:f7036819e80c8462660ae3',
    messagingSenderId: '252795060186',
    projectId: 'nexus-chatapp-prototype',
    storageBucket: 'nexus-chatapp-prototype.firebasestorage.app',
    iosBundleId: 'nexuschat.com.pk.nexusChat',
  );
}
